# Generated by Django 5.1.3 on 2024-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start_time', models.FloatField(help_text='Время начала (сек.)')),
                ('end_time', models.FloatField(help_text='Время окончания (сек.)')),
            ],
        ),
    ]
