# Generated by Django 5.1.3 on 2024-12-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0002_alter_subtitle_options_subtitle_film_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='character',
            field=models.CharField(blank=True, max_length=100, verbose_name='Персонаж'),
        ),
    ]
